Update sdk 2.8 and implement new webview sync
UMI3D/UMI3D-BROWSER pull request #76
Opened 2024-04-30 13:02 UTC by Quentin-Tran

2024-04-30 13:39 UTC, RomainTirbisch commented on UMI3D-BROWSER/Assets/Dependencies/UMI3D SDK/Dependencies/Runtime/LoaderUtils/Runtime/MRTKShaderUtils.cs
Are comments expected here ?

2024-04-30 13:41 UTC, RomainTirbisch commented on UMI3D-BROWSER/Assets/Dependencies/UnityGeckoWebView/Sample/UnityGeckoWebViewSearch.cs
Header have been removed

2024-04-30 13:41 UTC, RomainTirbisch commented on UMI3D-BROWSER/Assets/Dependencies/UnityGeckoWebView/Scripts/UnityGeckoWebView.cs
Header have been removed

2024-04-30 13:41 UTC, RomainTirbisch commented on UMI3D-BROWSER/Assets/Dependencies/UnityGeckoWebView/Scripts/UnityGeckoWebViewBounds.cs
Header have been removed

2024-04-30 13:42 UTC, RomainTirbisch commented on UMI3D-BROWSER/Assets/Dependencies/UnityGeckoWebView/Scripts/UnityGeckoWebViewCallback.cs
Header have been removed

2024-04-30 13:42 UTC, RomainTirbisch commented on UMI3D-BROWSER/Assets/Dependencies/UnityGeckoWebView/Scripts/UnityGeckoWebViewInput.cs
Header have been removed

2024-04-30 13:43 UTC, RomainTirbisch requested changes
Some header have been removed

2024-04-30 13:59 UTC, Quentin-Tran commented on UMI3D-BROWSER/Assets/Dependencies/UMI3D SDK/Dependencies/Runtime/LoaderUtils/Runtime/MRTKShaderUtils.cs
Yes

2024-04-30 14:01 UTC, Quentin-Tran commented on UMI3D-BROWSER/Assets/Dependencies/UnityGeckoWebView/Sample/UnityGeckoWebViewSearch.cs
"bien vu" as we say in French !

2024-05-02 07:37 UTC, RomainTirbisch approved these changes

2024-05-02 07:37 UTC, merged